image: s50600822/bazel:18

pipelines:
  default:
    - step:
        size: 2x # We exhaust our memory otherwise
        script:
          - bazel version
          - bazel build //src:bazel --verbose_failures=true --sandbox_debug
